app/blueprints/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Email, Optional, Length, EqualTo, ValidationError

from app.blueprints.users.model import User


class RegistrationFormUser(FlaskForm):
    """Creates the user form """

    name=StringField("Username", validators=[DataRequired("Please Enter your User Name")])
    email=EmailField("Email_Address", validators=[DataRequired("This Field reuires a valid email_address"),
                                                  Email("This field requires a valid email address")])
    password=PasswordField('Password',
                           validators=[DataRequired("kindly enter your password"),
                                       Length(min=8,max=16,
                                                   message="Please make sure your password\
                                                           is atleast 8 characters long")])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])

    address_1=StringField('Address_1', validators=[DataRequired("please enter your address")])
    address_2=StringField('Address_2', validators=[Optional()])
    city =StringField('City',validators=[DataRequired("Please Enter your city name")])
    postal_code =StringField('Zip Code', validators=[DataRequired('Please Enter your zip Code'),
                                                     Length(min=6,max=6,
                                                                 message='The zip code shoudl be 6 digits long')])


    mobile_phone=StringField('Phone Number', validators=[DataRequired(), Length(min=10, max=10)])
    submit = SubmitField('Register')


    def validate_email(self,email):
        """Check if the user is already registered WTF forms anything
        with Validate_XXX with raise a custom error message"""

        user = User.check_user_identity(identity=email.data)
        if user is not None:
            raise ValidationError("Please use a different email-address")


class RegisterDoctorForm(RegistrationFormUser,FlaskForm):
    """Creates the Doctor Registration Form"""

    registration_number = StringField('Registration Number', validators=[DataRequired("Please Enter your registration\
                                                                                      Number")])
    state = StringField('State', validators=[DataRequired('Enter your State of Registration')])
    year_of_registration = StringField('Year Of Registration', validators=[DataRequired('Enter your year of\
                                                                                       Registration'),
                                                                           Length(min=4,max=4)])

class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

app/__init__.py
from logging.handlers import RotatingFileHandler

from flask import Flask

from app.blueprints.users import user
from app.config import TestingConfig, DevelopmentConfig, Config
from app.extensions import db,migrate,login_manager


def create_app(config_settings=Config):

    app = Flask(__name__, instance_relative_config='')
    app.config.from_object(config_settings)
    handler = RotatingFileHandler(app.config.get('LOGGING_LOCATION'), maxBytes=10240,backupCount=10 )
    handler.setLevel(app.config.get('LOGGING_LEVEL'))
    formatter = handler.setFormatter(app.config.get('LOGGING_FORMAT'))
    handler.setFormatter(formatter)

    app.register_blueprint(user)

    app.logger.addHandler(handler)

    error(app)
    extensions(app)


    return app



def extensions(app):

    with app.test_request_context():
        login_manager.init_app(app)
        db.init_app(app)
        migrate.init_app(app,db)



def error(app):
    """"""
    @app.errorhandler(500)
    def internal_server_error(error):
        """Handles the 500 Error"""

        app.logger.error('Server Error: %s', (error))

    @app.errorhandler(404)
    def file_not_found(error):

        app.logger.error('Page Not Found: %s', (error))

app/blueprints/users/__init__.py
from flask import Blueprint

user = Blueprint('user',__name__, template_folder="/templates")

from app.blueprints.users import views

app/blueprints/users/views.py
from flask import render_template, url_for, flash, request
from werkzeug.urls import url_parse
from werkzeug.utils import redirect

from app.blueprints.users import user
from app.blueprints.users.forms import LoginForm, RegistrationFormUser
from app.blueprints.users.model import User
from flask_login import current_user,login_user,logout_user
from app.extensions import db

@user.route("/")
def index():
    return render_template('index/index.html')

@user.route("/login", methods=['GET','POST'])
def login():
    """End point for Login"""

    if current_user.is_authenticated:
        return redirect(url_for('user.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.check_user_identity(identity=form.email.data)
        if user is None or not user.decrypt_password(password=form.password.data):
            flash( 'Invalid email or password' )
            return redirect(url_for('login'))
        login_user(user)
        next_page = request.args.get('next_page')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('index')
        return redirect(next_page)
        return redirect(url_for('user.index'))
    return render_template('user/login.html', title='Sign In', form=form)



@user.route("/register", methods=['GET','POST'])
def registration():
    """End point for Registration"""

    if current_user.is_authenticated:
        return redirect(url_for('user.index'))
    form = RegistrationFormUser()

    if form.validate_on_submit():
        data = {"name":form.name.data,"email":form.email.data,"password":form.password.data,
                "address_1":form.address_1.data,"address_2":form.address_2.data,
                "city":form.city.data,"postal_code":form.postal_code.data,"mob_phone":form.mobile_phone.data}
        user = User(**data)
        user.save()
        flash("Congratulations you have have successfully registered")
        return redirect(url_for('user.login'))
    return render_template('user/registration.html', title='Sign Up', form=form)


@user.route("/logout", methods=['GET','POST'])
def logout():
    """Logs the user out"""

    logout_user()
    return redirect(url_for('user.index'))

app/templates/doctors/member1.html
<div class="cbp-l-member-img">
	<img src="img/team/1.jpg" alt="">
</div>
<div class="cbp-l-member-info">
	<div class="cbp-l-member-name">Alice Grue</div>
	<div class="cbp-l-member-position">Psychiatrist</div>
	<div class="cbp-l-member-desc">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, perspiciatis, corporis, iusto a saepe iste ea odit quas fugit amet nisi adipisci excepturi ipsam quae asperiores sit blanditiis sunt ducimus magni eos non et quos dignissimos quaerat aspernatur. Enim, temporibus, ullam, vitae, accusantium veniam ut odio magni nobis animi ratione eaque at aliquam eos error quas eum unde laudantium quisquam dolores voluptas velit corporis fuga! Error, soluta, consequatur, excepturi earum laudantium ab magnam vitae eligendi consectetur dicta quo nesciunt eveniet facere iusto praesentium aliquid impedit tempora nobis deleniti fugiat corporis maiores cupiditate provident veritatis quod odio nulla vel ratione quas.
	</div>
</div>

app/templates/doctors/member2.html
<div class="cbp-l-member-img">
	<img src="img/team/2.jpg" alt="">
</div>
<div class="cbp-l-member-info">
	<div class="cbp-l-member-name">Joseph Murphy</div>
	<div class="cbp-l-member-position">Cardiologist</div>
	<div class="cbp-l-member-desc">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, perspiciatis, corporis, iusto a saepe iste ea odit quas fugit amet nisi adipisci excepturi ipsam quae asperiores sit blanditiis sunt ducimus magni eos non et quos dignissimos quaerat aspernatur. Enim, temporibus, ullam, vitae, accusantium veniam ut odio magni nobis animi ratione eaque at aliquam eos error quas eum unde laudantium quisquam dolores voluptas velit corporis fuga! Error, soluta, consequatur, excepturi earum laudantium ab magnam vitae eligendi consectetur dicta quo nesciunt eveniet facere iusto praesentium aliquid impedit tempora nobis deleniti fugiat corporis maiores cupiditate provident veritatis quod odio nulla vel ratione quas.
	</div>
</div>

app/templates/doctors/member3.html
<div class="cbp-l-member-img">
	<img src="img/team/3.jpg" alt="">
</div>
<div class="cbp-l-member-info">
	<div class="cbp-l-member-name">Alison Davis</div>
	<div class="cbp-l-member-position">Cardiologist</div>
	<div class="cbp-l-member-desc">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, perspiciatis, corporis, iusto a saepe iste ea odit quas fugit amet nisi adipisci excepturi ipsam quae asperiores sit blanditiis sunt ducimus magni eos non et quos dignissimos quaerat aspernatur. Enim, temporibus, ullam, vitae, accusantium veniam ut odio magni nobis animi ratione eaque at aliquam eos error quas eum unde laudantium quisquam dolores voluptas velit corporis fuga! Error, soluta, consequatur, excepturi earum laudantium ab magnam vitae eligendi consectetur dicta quo nesciunt eveniet facere iusto praesentium aliquid impedit tempora nobis deleniti fugiat corporis maiores cupiditate provident veritatis quod odio nulla vel ratione quas.
	</div>
</div>

app/templates/doctors/member4.html
<div class="cbp-l-member-img">
	<img src="img/team/4.jpg" alt="">
</div>
<div class="cbp-l-member-info">
	<div class="cbp-l-member-name">Adam Taylor</div>
	<div class="cbp-l-member-position">Neurologist</div>
	<div class="cbp-l-member-desc">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum, perspiciatis, corporis, iusto a saepe iste ea odit quas fugit amet nisi adipisci excepturi ipsam quae asperiores sit blanditiis sunt ducimus magni eos non et quos dignissimos quaerat aspernatur. Enim, temporibus, ullam, vitae, accusantium veniam ut odio magni nobis animi ratione eaque at aliquam eos error quas eum unde laudantium quisquam dolores voluptas velit corporis fuga! Error, soluta, consequatur, excepturi earum laudantium ab magnam vitae eligendi consectetur dicta quo nesciunt eveniet facere iusto praesentium aliquid impedit tempora nobis deleniti fugiat corporis maiores cupiditate provident veritatis quod odio nulla vel ratione quas.
	</div>
</div>

app/templates/footer.html
<footer>
  <p>Posted by: Hege Refsnes</p>
  <p>Contact information: <a href="mailto:someone@example.com">
  someone@example.com</a>.</p>
</footer>

app/templates/index/index-form.html
{% extends "layouts/layouts.html" %}


{% block content %}


<form action="" method="post" role="form" class="contactForm lead">
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>First Name</label>
        <input type="text" name="first_name" id="first_name" class="form-control input-md" data-rule="minlen:3" data-msg="Please enter at least 3 chars">
        <div class="validation"></div>
      </div>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Last Name</label>
        <input type="text" name="last_name" id="last_name" class="form-control input-md" data-rule="minlen:3" data-msg="Please enter at least 3 chars">
        <div class="validation"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Email</label>
        <input type="email" name="email" id="email" class="form-control input-md" data-rule="email" data-msg="Please enter a valid email">
        <div class="validation"></div>
      </div>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Phone number</label>
        <input type="text" name="phone" id="phone" class="form-control input-md" data-rule="required" data-msg="The phone number is required">
        <div class="validation"></div>
      </div>
    </div>
  </div>

  <input type="submit" value="Submit" class="btn btn-skin btn-block btn-lg">

  <p class="lead-footer">* We'll contact you by phone & email later</p>

</form>


{% endblock %}

app/templates/index/index-video.html
{% extends index.html%}


{% block content %}


{%end block %}

app/templates/index/index.html
{% extends "layouts/layouts.html" %}

{% block content %}
<div class="container">
<h1>My Lame site</h1>
    <p>Hello, and welcome to my lame site! I'm so glad you're here. I'm so lonely.</p>
</div>
{% endblock %}

app/templates/layouts/layout_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Medicio landing page template for Health niche</title>

  <!-- css -->
  <link href="static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link href="static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link rel="static/stylesheet" type="text/css" href="plugins/cubeportfolio/css/cubeportfolio.min.css">
  <link href="static/css/nivo-lightbox.css" rel="stylesheet" />
  <link href="static/css/nivo-lightbox-theme/default/default.css" rel="stylesheet" type="text/css" />
  <link href="static/css/owl.carousel.css" rel="stylesheet" media="screen" />
  <link href="static/css/owl.theme.css" rel="stylesheet" media="screen" />
  <link href="static/css/animate.css" rel="stylesheet" />
  <link href="static/css/style.css" rel="stylesheet">

  <!-- boxed bg -->
  <link id="bodybg" href="static/bodybg/bg1.css" rel="stylesheet" type="text/css" />
  <!-- template skin -->
  <link id="t-colors" href="static/color/default.css" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Medicio
    Theme URL: https://bootstrapmade.com/medicio-free-bootstrap-theme/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>
  {% block content %}{% endblock %}
  {% include 'footer.html' %}
</body>
</html>

app/templates/layouts/layouts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Medicio landing page template for Health niche</title>

  <!-- css -->
  <link href="static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link href="static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link rel="static/stylesheet" type="text/css" href="plugins/cubeportfolio/css/cubeportfolio.min.css">
  <link href="static/css/nivo-lightbox.css" rel="stylesheet" />
  <link href="static/css/nivo-lightbox-theme/default/default.css" rel="stylesheet" type="text/css" />
  <link href="static/css/owl.carousel.css" rel="stylesheet" media="screen" />
  <link href="static/css/owl.theme.css" rel="stylesheet" media="screen" />
  <link href="static/css/animate.css" rel="stylesheet" />
  <link href="static/css/style.css" rel="stylesheet">

  <!-- boxed bg -->
  <link id="bodybg" href="static/bodybg/bg1.css" rel="stylesheet" type="text/css" />
  <!-- template skin -->
  <link id="t-colors" href="static/color/default.css" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Medicio
    Theme URL: https://bootstrapmade.com/medicio-free-bootstrap-theme/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>
  {% include 'nav.html' %}
  {% block content %}{% endblock %}
  {% include 'footer.html' %}
</body>
</html>

app/templates/nav.html
<body id="page-top" data-spy="scroll" data-target=".navbar-custom">

  <div id="wrapper">

    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="top-area">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-md-6">
              <p class="bold text-left">Monday - Saturday, 8am to 10pm </p>
            </div>
            <div class="col-sm-6 col-md-6">
              <p class="bold text-right">Call us now +62 008 65 001</p>
            </div>
          </div>
        </div>
      </div>
      <div class="container navigation">

        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
          <a class="navbar-brand" href="templates/index/index.html">
                    <img src="static/img/logo.png" alt="" width="150" height="40" />
                </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#intro">Home</a></li>
            <li><a href="#service">Service</a></li>
            <li><a href="#doctor">Doctors</a></li>
            <li><a href="#facilities">Facilities</a></li>
            <li><a href="#pricing">Pricing</a></li>
            <a href="{{ url_for('user.index') }}">Home</a>
        {% if current_user.is_anonymous %}
        <a href="{{ url_for('user.login') }}">Login</a>
        {% else %}
        <a href="{{ url_for('user.logout') }}">Logout</a>
        {% endif %}
            <li><a href="#signup">Sign Up</a></li>



            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="badge custom-badge red pull-right">Extra</span>More <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="index/index.html">Home CTA</a></li>
                <li><a href="index/index-form.html">Home Form</a></li>
                <li><a href="index/index-video.html">Home video</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>
  </div>

app/templates/user/login.html
{% extends "layouts/layout_one.html" %}


{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/user/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/user/registration.html
{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}<br>
            {% for error in form.name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
          <p>
            {{ form.address_1.label }}<br>
            {{ form.address_1(size=64) }}<br>
            {% for error in form.address_1.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
          <p>
            {{ form.address_2.label }}<br>
            {{ form.address_2(size=64) }}<br>
            {% for error in form.address_2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
         <p>
            {{ form.city.label }}<br>
            {{ form.city(size=32) }}<br>
            {% for error in form.city.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
          <p>
            {{ form.postal_code.label }}<br>
            {{ form.postal_code(size=32) }}<br>
            {% for error in form.postal_code.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
           <p>
            {{ form.postal_code.label }}<br>
            {{ form.postal_code(size=32) }}<br>
            {% for error in form.postal_code.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>

         <p>
            {{ form.mobile_phone.label }}<br>
            {{ form.mobile_phone(size=32) }}<br>
            {% for error in form.postal_code.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}